#!/usr/bin/env bash
# CI/CD helper: write deploy/.env.prod from environment variables.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env.prod"

required_vars=(
  APP_HOST
  NEXTAUTH_URL
  NEXT_PUBLIC_SUPABASE_URL
  NEXT_PUBLIC_SUPABASE_ANON_KEY
  SUPABASE_SERVICE_ROLE_KEY
  NEXTAUTH_SECRET
  NOTIFICATION_HUB_BASE_URL
  NOTIFICATION_HUB_OAUTH_TOKEN_URI
  NOTIFICATION_HUB_OAUTH_CLIENT_ID
  NOTIFICATION_HUB_OAUTH_CLIENT_SECRET
  IMAGE
)

for var in "${required_vars[@]}"; do
  if [[ -z "${!var:-}" ]]; then
    echo "Missing required env var: ${var}"
    exit 1
  fi
done

NOTIFICATION_HUB_TENANT_ID="${NOTIFICATION_HUB_TENANT_ID:-s2a}"

cat > "${ENV_FILE}" <<EOF
APP_HOST=${APP_HOST}
NEXTAUTH_URL=${NEXTAUTH_URL}
NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NOTIFICATION_HUB_BASE_URL=${NOTIFICATION_HUB_BASE_URL}
NOTIFICATION_HUB_TENANT_ID=${NOTIFICATION_HUB_TENANT_ID}
NOTIFICATION_HUB_OAUTH_ENABLED=true
NOTIFICATION_HUB_OAUTH_TOKEN_URI=${NOTIFICATION_HUB_OAUTH_TOKEN_URI}
NOTIFICATION_HUB_OAUTH_CLIENT_ID=${NOTIFICATION_HUB_OAUTH_CLIENT_ID}
NOTIFICATION_HUB_OAUTH_CLIENT_SECRET=${NOTIFICATION_HUB_OAUTH_CLIENT_SECRET}
IMAGE=${IMAGE}
EOF

echo "Wrote ${ENV_FILE}"
