#!/usr/bin/env bash
# CI/CD helper: write deploy/.env.prod from environment variables.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env.prod"

required_vars=(
  APP_HOST
  NEXTAUTH_URL
  NEXTAUTH_SECRET
  DB_PASSWORD
  NOTIFICATION_HUB_BASE_URL
  NOTIFICATION_HUB_OAUTH_TOKEN_URI
  NOTIFICATION_HUB_OAUTH_CLIENT_ID
  NOTIFICATION_HUB_OAUTH_CLIENT_SECRET
  IMAGE
)

for var in "${required_vars[@]}"; do
  if [[ -z "${!var:-}" ]]; then
    echo "Missing required env var: ${var}"
    exit 1
  fi
done

NOTIFICATION_HUB_TENANT_ID="${NOTIFICATION_HUB_TENANT_ID:-s2a}"
DB_USER="${DB_USER:-s2a}"
DB_NAME="${DB_NAME:-s2a}"
# Escape $ for docker compose variable interpolation in DATABASE_URL consumers
DB_PASSWORD_ESC="${DB_PASSWORD//\$/$$}"

cat > "${ENV_FILE}" <<EOF
APP_HOST=${APP_HOST}
NEXTAUTH_URL=${NEXTAUTH_URL}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD_ESC}
DB_NAME=${DB_NAME}
DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD_ESC}@db:5432/${DB_NAME}
NOTIFICATION_HUB_BASE_URL=${NOTIFICATION_HUB_BASE_URL}
NOTIFICATION_HUB_TENANT_ID=${NOTIFICATION_HUB_TENANT_ID}
NOTIFICATION_HUB_OAUTH_ENABLED=true
NOTIFICATION_HUB_OAUTH_TOKEN_URI=${NOTIFICATION_HUB_OAUTH_TOKEN_URI}
NOTIFICATION_HUB_OAUTH_CLIENT_ID=${NOTIFICATION_HUB_OAUTH_CLIENT_ID}
NOTIFICATION_HUB_OAUTH_CLIENT_SECRET=${NOTIFICATION_HUB_OAUTH_CLIENT_SECRET}
IMAGE=${IMAGE}
EOF

echo "Wrote ${ENV_FILE}"
